"use client";

import React, { useCallback, useLayoutEffect, useRef, useState, useMemo } from "react";
import { Rewind, Target, BarChart2 } from "lucide-react";
import { Hoverable } from "@/components/scm/widgets/Hoverable";
import { formatDistribution, formatFunctionalForm } from "@/lib/scmdisplay";
import type { SCMVariable, SCMEdge, SCMSchema } from "@/types";
import SCMDAGView from "./widgets/SCMDAGView";

interface SCMOverviewProps {
  variables: SCMVariable[];
  edges: SCMEdge[];
}

const SUBSCRIPTS = "₀₁₂₃₄₅₆₇₈₉";
const toSubscript = (n: number) => String(n).split("").map((d) => SUBSCRIPTS[+d]).join("");

const HOVERABLE_DESCRIPTIONS: Record<string, string> = {
  scm: "The SCM is the ground truth. It defines the exact functions and noise distributions that generate all the data.",
  dag: "The DAG is a visual map of cause and effect. The arrows show which variables influence one another.",
  obs: "Explore the empirical data generated by the SCM to analyse distributions, correlations, or add new variables into the system.",
  int: "Simulate an action by forcing variables to specific states using the do-operator and observe how the system responds.",
  cf: "Evaluate alternate scenarios for an observation by freezing its exogenous noise while applying the do-operator to the model.",
  data: "The empirical evidence gathered from the observational layer.",
  assume: "Constraints and domain knowledge.",
  query: "Specific questions you are trying to answer.",
  results: "Final computed effect based on your model and query.",
};

type Rect = {
  left: number;
  top: number;
  right: number;
  bottom: number;
  width: number;
  height: number;
  centerX: number;
  centerY: number;
};

function measure(el: HTMLElement, container: HTMLElement): Rect {
  const a = el.getBoundingClientRect();
  const c = container.getBoundingClientRect();
  const left = a.left - c.left;
  const top = a.top - c.top;
  return {
    left,
    top,
    right: left + a.width,
    bottom: top + a.height,
    width: a.width,
    height: a.height,
    centerX: left + a.width / 2,
    centerY: top + a.height / 2,
  };
}

export default function SCMOverview({ variables }: SCMOverviewProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  const scmRef = useRef<HTMLDivElement>(null);
  const dagRef = useRef<HTMLDivElement>(null);
  const obsRef = useRef<HTMLDivElement>(null);
  const intRef = useRef<HTMLDivElement>(null);
  const cfRef = useRef<HTMLDivElement>(null);
  const dataRef = useRef<HTMLDivElement>(null);
  const assumeRef = useRef<HTMLDivElement>(null);
  const queryRef = useRef<HTMLDivElement>(null);
  const resultsRef = useRef<HTMLDivElement>(null);

  const [rects, setRects] = useState<Record<string, Rect> | null>(null);

  const schemaKey = useMemo(() => variables.map((v) => v.id).join("-"), [variables]);

  const recompute = useCallback(() => {
    const container = containerRef.current;
    if (!container) return;
    const refs: Record<string, React.RefObject<HTMLDivElement>> = {
      scm: scmRef,
      dag: dagRef,
      obs: obsRef,
      int: intRef,
      cf: cfRef,
      data: dataRef,
      assume: assumeRef,
      query: queryRef,
      results: resultsRef,
    };
    const next: Record<string, Rect> = {};
    (Object.keys(refs) as (keyof typeof refs)[]).forEach((key) => {
      const el = refs[key].current;
      if (el) next[key] = measure(el, container);
    });
    setRects(next);
  }, []);

  useLayoutEffect(() => {
    recompute();
    const ro = new ResizeObserver(() => recompute());
    if (containerRef.current) ro.observe(containerRef.current);
    if (scmRef.current) ro.observe(scmRef.current);
    window.addEventListener("resize", recompute);
    return () => {
      ro.disconnect();
      window.removeEventListener("resize", recompute);
    };
  }, [recompute, schemaKey]);

  return (
    <div className="w-full pb-3">
      <div className="w-full overflow-x-auto [scrollbar-width:thin] sticky bottom-0">
        <div ref={containerRef} className="relative mx-auto w-fit min-w-max px-9 pt-9 pb-[7px]">
        {rects && (() => {
          const busY = Math.max(rects.data.bottom, rects.assume.bottom, rects.query.bottom) + 20;
          
          const scmToDagY = rects.dag.centerY;
          const scmToDagMidX = (rects.scm.right + rects.dag.left) / 2;

          return (
            <svg className="pointer-events-none absolute inset-0 z-0 h-full w-full overflow-visible">
              <defs>
                <marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="5" markerHeight="5" orient="auto">
                  <path d="M 0 0 L 10 5 L 0 10 z" fill="#94A3B8" />
                </marker>
              </defs>

              {/* SCM -> DAG */}
              <path d={`M ${rects.scm.right} ${scmToDagY} L ${rects.dag.left - 2} ${scmToDagY}`} fill="none" stroke="#94A3B8" strokeWidth={1} markerEnd="url(#arrow)" />
              
              <rect x={scmToDagMidX - 38} y={scmToDagY - 18} width="76" height="25" fill="#ffffff" />
              <text x={scmToDagMidX} y={scmToDagY - 4} textAnchor="middle" fill="#64748B" fontSize="9" fontWeight={500}>structural</text>
              <text x={scmToDagMidX} y={scmToDagY + 7} textAnchor="middle" fill="#64748B" fontSize="9" fontWeight={500}>constraints</text>

              {/* SCM -> Hierarchy Layers */}
              {(() => {
                const trunkX = rects.scm.centerX;
                const branchY = rects.scm.bottom + (rects.obs.top - rects.scm.bottom) / 2;
                return (
                  <>
                    <path d={`M ${trunkX} ${rects.scm.bottom} L ${trunkX} ${branchY}`} fill="none" stroke="#CBD5E1" strokeWidth={1} />
                    <path d={`M ${rects.obs.centerX} ${branchY} L ${rects.cf.centerX} ${branchY}`} fill="none" stroke="#CBD5E1" strokeWidth={1} />
                    <path d={`M ${rects.obs.centerX} ${branchY} L ${rects.obs.centerX} ${rects.obs.top - 5}`} fill="none" stroke="#CBD5E1" strokeWidth={1} markerEnd="url(#arrow)" />
                    <path d={`M ${rects.int.centerX} ${branchY} L ${rects.int.centerX} ${rects.int.top - 5}`} fill="none" stroke="#CBD5E1" strokeWidth={1} markerEnd="url(#arrow)" />
                    <path d={`M ${rects.cf.centerX} ${branchY} L ${rects.cf.centerX} ${rects.cf.top - 5}`} fill="none" stroke="#CBD5E1" strokeWidth={1} markerEnd="url(#arrow)" />
                  </>
                );
              })()}

              {/* Hierarchy -> Inputs */}
              <path d={`M ${rects.data.centerX} ${rects.obs.bottom} L ${rects.data.centerX} ${rects.data.top - 5}`} fill="none" stroke="#CBD5E1" strokeWidth={1} markerEnd="url(#arrow)" />

              {/* Inputs -> Results */}
              <path d={`M ${rects.data.centerX} ${rects.data.bottom} L ${rects.data.centerX} ${busY}`} fill="none" stroke="#CBD5E1" strokeWidth={1} />
              <path d={`M ${rects.assume.centerX} ${rects.assume.bottom} L ${rects.assume.centerX} ${busY}`} fill="none" stroke="#CBD5E1" strokeWidth={1} />
              <path d={`M ${rects.query.centerX} ${rects.query.bottom} L ${rects.query.centerX} ${busY}`} fill="none" stroke="#CBD5E1" strokeWidth={1} />

              {/* Bus for arrows */}
              <path d={`M ${rects.data.centerX} ${busY} L ${rects.query.centerX} ${busY}`} fill="none" stroke="#CBD5E1" strokeWidth={1} />

              {/* drop into results*/}
              <path d={`M ${rects.results.left + rects.results.width * 0.25} ${busY} L ${rects.results.left + rects.results.width * 0.25} ${rects.results.top - 5}`} fill="none" stroke="#CBD5E1" strokeWidth={1} markerEnd="url(#arrow)" />
              <path d={`M ${rects.results.centerX} ${busY} L ${rects.results.centerX} ${rects.results.top - 5}`} fill="none" stroke="#CBD5E1" strokeWidth={1} markerEnd="url(#arrow)" />
              <path d={`M ${rects.results.right - rects.results.width * 0.25} ${busY} L ${rects.results.right - rects.results.width * 0.25} ${rects.results.top - 5}`} fill="none" stroke="#CBD5E1" strokeWidth={1} markerEnd="url(#arrow)" />

              {/* Query <-> DAG / Counterfactual */}
              <path d={`M ${rects.query.centerX} ${rects.query.top} L ${rects.query.centerX} ${rects.dag.bottom}`} fill="none" stroke="#94A3B8" strokeWidth={1} strokeDasharray="4 3" markerEnd="url(#arrow)" />
              <path d={`M ${rects.query.centerX} ${rects.cf.centerY} L ${rects.cf.right + 5} ${rects.cf.centerY}`} fill="none" stroke="#94A3B8" strokeWidth={1} strokeDasharray="4 3" markerEnd="url(#arrow)" />
            </svg>
          );
        })()}

        {/* Legend Nodes */}
        <div className="relative z-10 flex flex-col gap-[52px] w-full">
          <div className="absolute -left-8 top-8 flex flex-col gap-5">
            <div className="flex h-[37px] w-[90px] items-center justify-center rounded-lg border border-dashed border-[#8BA3D1] bg-[#F1F5FB] text-[11px] font-semibold text-[#4F70B0]">
              Unobserved
            </div>
            <div className="flex h-[46px] w-[90px] flex-col items-center justify-center rounded-lg border border-dashed border-[#D9C4A9] bg-[#FCF8F2] text-center text-[11px] font-semibold leading-snug text-[#B89467]">
              Potentially
              <br />
              Known
            </div>
          </div>

          {/*SCM + DAG */}
          <div className="flex w-full items-start justify-between pl-[115px] pr-[33px] gap-[140px]">
            <Hoverable ref={scmRef} title="Structural Causal Model" description={HOVERABLE_DESCRIPTIONS.scm} side="bottom" className="w-fit min-w-[410px] flex-shrink-0">
              <h2 className="mb-3 text-[15px] font-bold tracking-tight text-[#4F70B0]">Structural Causal Model</h2>
              <div className="relative w-full rounded-xl border-[1.5px] border-dashed border-[#8BA3D1] bg-[#F2F6FE] py-3 shadow-sm">
                <div className="mb-5 flex items-center justify-between px-5">
                  <div className="flex items-center gap-2.5">
                    <span className="relative flex h-2.5 w-2.5">
                      <span className="absolute inline-flex h-full w-full animate-ping [animation-duration:2s] rounded-full bg-emerald-400 opacity-75" />
                      <span className="relative inline-flex h-2.5 w-2.5 rounded-full bg-emerald-500" />
                    </span>
                    <span className="text-[13px] font-semibold text-[#374E74]">Active Variables</span>
                  </div>
                  <span className="font-serif text-lg font-bold italic text-[#4F70B0]">
                    P<sub className="ml-[1px] text-[12px] font-bold">
                      <sub className="ml-[1px] text-[12px] font-bold">
                      {variables.map((_, i) => `N${toSubscript(i + 1)}`).join(",")}
                    </sub>
                    </sub>
                  </span>
                </div>
                
                <div className="w-full overflow-x-auto pb-2 px-5 [scrollbar-width:thin] [&::-webkit-scrollbar]:h-1 [&::-webkit-scrollbar-thumb]:rounded-full [&::-webkit-scrollbar-thumb]:bg-[#8BA3D1]/50">
                  <div className="grid grid-cols-[max-content_auto_1fr] min-w-max items-center gap-x-5 gap-y-3.5 font-mono">
                    {variables.map((v, i) => (
                      <React.Fragment key={v.id}>
                        <div className="flex items-center gap-3.5 pl-2">
                          <span className="text-[12px] font-bold text-[#395A96]">{v.name}</span>
                          <span className="text-[12px] text-[#94A3B8]">←</span>
                          <span className="text-[12px] text-[#395A96]">{formatFunctionalForm(v, i, { variables } as SCMSchema)}</span>
                        </div>
                        {i === 0 && (
                          <div
                            className="w-[1px] justify-self-center bg-[#8BA3D1]/40"
                            style={{ gridRow: `span ${variables.length}` }}
                          />
                        )}
                        <div className="flex items-center justify-self-end rounded-lg border border-[#CBD5E1] bg-white px-3.5 py-1 text-[11px] text-[#64748B] shadow-sm">
                          <span className="mr-1.5 font-semibold text-[#94A3B8]">{v.noise.name} ~</span>
                          {formatDistribution(v.noise.distribution)}
                        </div>
                      </React.Fragment>
                    ))}
                  </div>
                </div>
              </div>
            </Hoverable>

            <Hoverable ref={dagRef} title="DAG" description={HOVERABLE_DESCRIPTIONS.dag} side="bottom" className="w-[285px] flex-shrink-0">
                <h2 className="mb-3 text-[15px] font-bold tracking-tight text-[#C48A5E]">DAG</h2>
                <div className="h-[230px] w-full rounded-xl border-[1.5px] border-dashed border-[#D9C4A9] bg-white shadow-sm overflow-hidden">
                  <SCMDAGView key={schemaKey} variables={variables} showToggle={false} />
                </div>
              </Hoverable>
          </div>

          {/* hierarchy */}
          <div className="w-full flex justify-start pl-[115px]">
            <div className="w-fit rounded-xl border-[1.5px] border-dotted border-[#94A3B8] bg-white p-1.5">
              <div className="flex items-stretch gap-2.5">
                <Hoverable ref={obsRef} title="Observational" description={HOVERABLE_DESCRIPTIONS.obs} className="w-[180px] flex-shrink-0">
                  <div className="flex h-full flex-col items-center justify-center gap-2.5 rounded-lg border-[1.5px] border-dashed border-[#D9C4A9] bg-[#FCF8F2] py-4 shadow-sm">
                    <div className="flex items-center gap-1.5 text-[11px] font-bold text-[#B89467]">
                      <BarChart2 size={14} />
                      Observational
                    </div>
                    <div className="font-serif text-[16px] font-medium italic tracking-wide text-[#A37B4E]">
                      ℒ<sub className="text-[9px]">1</sub> : P<sub className="ml-0.5 text-[9px] font-bold">X</sub>
                    </div>
                  </div>
                </Hoverable>

                <Hoverable ref={intRef} title="Interventional" description={HOVERABLE_DESCRIPTIONS.int} className="w-[180px] flex-shrink-0">
                  <div className="flex h-full flex-col items-center justify-center gap-2.5 rounded-lg border-[1.5px] border-dashed border-[#D9C4A9] bg-[#FCF8F2] py-4 shadow-sm">
                    <div className="flex items-center gap-1.5 text-[11px] font-bold text-[#B89467]">
                      <Target size={14} />
                      Interventional
                    </div>
                    <div className="font-serif text-[16px] font-medium italic tracking-wide text-[#A37B4E]">
                      ℒ<sub className="text-[9px]">2</sub> : P
                      <sub className="ml-0.5 text-[9px]">
                        do(<span className="font-bold">X'</span>=x')
                      </sub>
                    </div>
                  </div>
                </Hoverable>

                <Hoverable ref={cfRef} title="Counterfactual" description={HOVERABLE_DESCRIPTIONS.cf} className="w-[180px] flex-shrink-0">
                  <div className="flex h-full flex-col items-center justify-center gap-2.5 rounded-lg border-[1.5px] border-dashed border-[#8BA3D1] bg-[#F2F6FE] py-4 shadow-sm">
                    <div className="flex items-center gap-1.5 text-[11px] font-bold text-[#4F70B0]">
                      <Rewind size={14} />
                      Counterfactual
                    </div>
                    <div className="flex items-center text-[16px] font-medium tracking-wide text-[#4F70B0]">
                      <span className="font-serif italic">
                        ℒ<sub className="text-[9px]">3</sub> : P
                      </span>
                      <div className="-ml-0.5 -mt-1 flex flex-col items-center justify-center">
                        <span className="font-serif text-[8px] italic leading-[10px]">
                          <span className="font-bold">X'</span>=x'
                        </span>
                        <sub className="font-serif text-[9px] italic leading-[10px]">
                          do(<span className="font-bold">X''</span>=x'')
                        </sub>
                      </div>
                    </div>
                  </div>
                </Hoverable>
              </div>
            </div>
          </div>

          {/* data/assumptions/query -> results nodes */}
          <div className="flex w-full min-w-max items-start justify-between pl-[115px] pr-[33px]">
            <div className="flex flex-1 justify-around pr-[33px]">
              <div className="flex justify-center">
                <Hoverable ref={dataRef} title="Data" description={HOVERABLE_DESCRIPTIONS.data}>
                  <div className="flex h-[42px] w-[115px] items-center justify-center rounded-xl border border-[#CBD5E1] bg-white text-[12px] font-bold text-[#475569] shadow-sm">
                    Data
                  </div>
                </Hoverable>
              </div>
              <div className="flex justify-center">
                <Hoverable ref={assumeRef} title="Assumptions" description={HOVERABLE_DESCRIPTIONS.assume}>
                  <div className="flex h-[42px] w-[115px] items-center justify-center rounded-xl border border-[#CBD5E1] bg-white text-[12px] font-bold text-[#475569] shadow-sm">
                    Assumptions
                  </div>
                </Hoverable>
              </div>
            </div>
            <div className="flex w-[230px] justify-center">
              <Hoverable ref={queryRef} title="Query" description={HOVERABLE_DESCRIPTIONS.query}>
                <div className="flex h-[42px] w-[115px] items-center justify-center rounded-xl border border-[#CBD5E1] bg-white text-[12px] font-bold text-[#475569] shadow-sm">
                  Query
                </div>
              </Hoverable>
            </div>
          </div>

          {/* Row 4: Results */}
          <div className="flex w-full justify-center pl-[123px] pr-[285px]">
            <Hoverable ref={resultsRef} title="Results" description={HOVERABLE_DESCRIPTIONS.results} side="top">
              <div className="flex h-[37px] w-[148px] items-center justify-center rounded-xl border border-[#8ad182] bg-[#E9FBEB] text-[12px] font-bold text-[#638863] shadow-sm">
                Results
              </div>
            </Hoverable>
          </div>
        </div>
        </div>
      </div>
    </div>
  );
}
